---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - backupconfig.sdbrett.com
  resources:
  - etcdbackups
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - backupconfig.sdbrett.com
  resources:
  - etcdbackups/finalizers
  verbs:
  - update
- apiGroups:
  - backupconfig.sdbrett.com
  resources:
  - etcdbackups/status
  verbs:
  - get
  - patch
  - update
